// Package wails_service_layer_test provides acceptance tests for Story 2.3:
// Wails Service Layer -- Bind PDF Core to Frontend.
//
// These are TDD RED PHASE tests -- they MUST fail until Story 2-3 is implemented.
//
// Test Levels: Unit (Go) -- source file content parsing + delegated test execution.
// No browser interaction required; all criteria are Go package validation.
//
// Run: cd tests/wails-service-layer && go test -v -count=1 ./...
package wails_service_layer_test

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// projectRoot returns the absolute path to the project root directory.
func projectRoot(t *testing.T) string {
	t.Helper()
	dir, err := os.Getwd()
	if err != nil {
		t.Fatalf("failed to get working directory: %v", err)
	}
	for {
		goModPath := filepath.Join(dir, "go.mod")
		if content, err := os.ReadFile(goModPath); err == nil {
			if strings.Contains(string(content), "module unipdf-debugger") {
				return dir
			}
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatalf("could not find project root (no go.mod with module unipdf-debugger found)")
		}
		dir = parent
	}
}

// readFile reads a file relative to the project root and returns its content.
func readFile(t *testing.T, relPath string) string {
	t.Helper()
	root := projectRoot(t)
	absPath := filepath.Join(root, relPath)
	content, err := os.ReadFile(absPath)
	if err != nil {
		t.Fatalf("failed to read %s: %v", relPath, err)
	}
	return string(content)
}

// ---------------------------------------------------------------------------
// AC#1: PDFService struct exists with correct methods
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// 2.3-UNIT-001 [P1]: PDFService.OpenFile() delegates to Inspector.Open()
// AC#1: Given a valid PDF, When PDFService.OpenFile(path) is called,
//       Then it delegates to Inspector.Open() and returns DocumentInfo
//       with non-empty TabID, correct FileName, PageCount > 0.
// ---------------------------------------------------------------------------

func TestPDFServiceOpenFile(t *testing.T) {
	root := projectRoot(t)

	// Run pdfservice unit test that validates OpenFile with valid PDF.
	// Delegates to internal/pdfservice/service_test.go::TestOpenFileValidPDF
	// which must exist and test:
	// - returns non-nil DocumentInfo
	// - DocumentInfo.TabID is non-empty (UUID generated by service)
	// - DocumentInfo.FileName == "minimal.pdf"
	// - DocumentInfo.PageCount >= 1
	// - no error returned
	cmd := exec.Command("go", "test", "-v", "-run", "TestOpenFileValidPDF", "-count=1", "./internal/pdfservice/...")
	cmd.Dir = root
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("[P1] 2.3-UNIT-001: PDFService.OpenFile() valid PDF test failed:\n%s", string(output))
	}

	if !strings.Contains(string(output), "PASS") {
		t.Fatalf("[P1] 2.3-UNIT-001: expected PASS in output but got:\n%s", string(output))
	}
}

// ---------------------------------------------------------------------------
// 2.3-UNIT-002 [P1]: PDFService.CloseDocument() delegates to Inspector.Close()
// AC#1: Given a previously opened document, When CloseDocument(tabID) is called,
//       Then it delegates to Inspector.Close() and returns nil error.
//       And calling again with the same tabID returns ErrDocumentNotFound.
// ---------------------------------------------------------------------------

func TestPDFServiceCloseDocument(t *testing.T) {
	root := projectRoot(t)

	// Run pdfservice unit test that validates CloseDocument.
	// Delegates to internal/pdfservice/service_test.go::TestCloseDocument*
	// which must exist and test:
	// - CloseDocument with valid tabID returns nil
	// - CloseDocument with unknown tabID returns error
	cmd := exec.Command("go", "test", "-v", "-run", "TestCloseDocument", "-count=1", "./internal/pdfservice/...")
	cmd.Dir = root
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("[P1] 2.3-UNIT-002: PDFService.CloseDocument() test failed:\n%s", string(output))
	}

	if !strings.Contains(string(output), "PASS") {
		t.Fatalf("[P1] 2.3-UNIT-002: expected PASS in output but got:\n%s", string(output))
	}
}

// ---------------------------------------------------------------------------
// 2.3-UNIT-003 [P1]: PDFService.GetTreeRoot() delegates to pdfcore
// AC#1: Given an opened document, When GetTreeRoot(tabID) is called,
//       Then it delegates to Inspector.GetTreeRoot() and returns TreeNode
//       with ID "root".
// ---------------------------------------------------------------------------

func TestPDFServiceGetTreeRoot(t *testing.T) {
	root := projectRoot(t)

	// Run pdfservice unit test that validates GetTreeRoot.
	// Delegates to internal/pdfservice/service_test.go::TestGetTreeRoot*
	// which must exist and test:
	// - returns non-nil TreeNode
	// - TreeNode.ID == "root"
	// - no error returned
	// - with unknown tabID returns error
	cmd := exec.Command("go", "test", "-v", "-run", "TestGetTreeRoot", "-count=1", "./internal/pdfservice/...")
	cmd.Dir = root
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("[P1] 2.3-UNIT-003: PDFService.GetTreeRoot() test failed:\n%s", string(output))
	}

	if !strings.Contains(string(output), "PASS") {
		t.Fatalf("[P1] 2.3-UNIT-003: expected PASS in output but got:\n%s", string(output))
	}
}

// ---------------------------------------------------------------------------
// 2.3-UNIT-004 [P1]: PDFService.GetChildren() delegates to pdfcore
// AC#1: Given an opened document, When GetChildren(tabID, "root") is called,
//       Then it delegates to Inspector.GetChildren() and returns non-empty
//       []*TreeNode slice.
// ---------------------------------------------------------------------------

func TestPDFServiceGetChildren(t *testing.T) {
	root := projectRoot(t)

	// Run pdfservice unit test that validates GetChildren.
	// Delegates to internal/pdfservice/service_test.go::TestGetChildren*
	// which must exist and test:
	// - returns non-empty TreeNode slice for valid tabID and "root" nodeID
	// - no error returned
	// - with unknown tabID returns error
	cmd := exec.Command("go", "test", "-v", "-run", "TestGetChildren", "-count=1", "./internal/pdfservice/...")
	cmd.Dir = root
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("[P1] 2.3-UNIT-004: PDFService.GetChildren() test failed:\n%s", string(output))
	}

	if !strings.Contains(string(output), "PASS") {
		t.Fatalf("[P1] 2.3-UNIT-004: expected PASS in output but got:\n%s", string(output))
	}
}

// ---------------------------------------------------------------------------
// 2.3-UNIT-005 [P1]: PDFService.GetObjectDetail() returns stub error
// AC#1: Given any input, When GetObjectDetail(tabID, nodeID) is called,
//       Then it returns a "not implemented" error (stub until Story 2-6).
// ---------------------------------------------------------------------------

func TestPDFServiceGetObjectDetail(t *testing.T) {
	root := projectRoot(t)

	// Run pdfservice unit test that validates GetObjectDetail stub.
	// Delegates to internal/pdfservice/service_test.go::TestGetObjectDetail*
	// which must exist and test:
	// - returns error containing "not implemented"
	// - returns nil ObjectDetail
	cmd := exec.Command("go", "test", "-v", "-run", "TestGetObjectDetail", "-count=1", "./internal/pdfservice/...")
	cmd.Dir = root
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("[P1] 2.3-UNIT-005: PDFService.GetObjectDetail() test failed:\n%s", string(output))
	}

	if !strings.Contains(string(output), "PASS") {
		t.Fatalf("[P1] 2.3-UNIT-005: expected PASS in output but got:\n%s", string(output))
	}
}

// ---------------------------------------------------------------------------
// 2.3-UNIT-006 [P1]: PDFService methods with invalid tabID return error
// AC#2: Given a PDFService method, When called with an unknown tabID,
//       Then it returns an error (propagated from pdfcore).
// ---------------------------------------------------------------------------

func TestPDFServiceInvalidTabID(t *testing.T) {
	root := projectRoot(t)

	// Run pdfservice unit tests for invalid tabID scenarios.
	// Delegates to internal/pdfservice/service_test.go tests matching "Unknown"
	// which must exist and test:
	// - CloseDocument with unknown tabID returns error
	// - GetTreeRoot with unknown tabID returns error
	// - GetChildren with unknown tabID returns error
	cmd := exec.Command("go", "test", "-v", "-run", "Unknown", "-count=1", "./internal/pdfservice/...")
	cmd.Dir = root
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("[P1] 2.3-UNIT-006: PDFService invalid tabID tests failed:\n%s", string(output))
	}

	if !strings.Contains(string(output), "PASS") {
		t.Fatalf("[P1] 2.3-UNIT-006: expected PASS in output but got:\n%s", string(output))
	}
}

// ---------------------------------------------------------------------------
// AC#1: Wails service registration in main.go
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// 2.3-INTG-001 [P1]: PDFService is registered in main.go via app.RegisterService()
// AC#1: Given main.go, When reviewed, Then PDFService is created and registered
//       using app.RegisterService() (NOT the Services: field in Options).
// ---------------------------------------------------------------------------

func TestMainGoRegistersPDFService(t *testing.T) {
	content := readFile(t, "main.go")

	// Must import pdfservice package
	if !strings.Contains(content, `"unipdf-debugger/internal/pdfservice"`) {
		t.Error("[P1] 2.3-INTG-001: main.go does not import internal/pdfservice")
	}

	// Must create PDFService instance via NewPDFService()
	if !strings.Contains(content, "pdfservice.NewPDFService()") {
		t.Error("[P1] 2.3-INTG-001: main.go does not call pdfservice.NewPDFService()")
	}

	// Must register using app.RegisterService()
	if !strings.Contains(content, "app.RegisterService(") {
		t.Error("[P1] 2.3-INTG-001: main.go does not call app.RegisterService()")
	}

	// Must use application.NewService() wrapper
	if !strings.Contains(content, "application.NewService(") {
		t.Error("[P1] 2.3-INTG-001: main.go does not call application.NewService()")
	}
}

// ---------------------------------------------------------------------------
// 2.3-INTG-002 [P1]: main.go does NOT use Services: field in application.Options
// AC#1: The app-shell test TestServicesFieldRemoved must still pass.
//       Services: field and application.NewService must not co-occur in Options.
// ---------------------------------------------------------------------------

func TestMainGoNoServicesField(t *testing.T) {
	content := readFile(t, "main.go")

	// The Services: field must not appear inside application.Options{...}
	// Look for "Services:" between "application.Options{" and the closing "}"
	if strings.Contains(content, "Services:") {
		t.Error("[P1] 2.3-INTG-002: main.go uses Services: field in application.Options -- use app.RegisterService() instead")
	}
}

// ---------------------------------------------------------------------------
// AC#3: Architecture compliance -- pdfservice is thin adapter
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// 2.3-INTG-003 [P1]: service.go exists in internal/pdfservice/
// AC#3: PDFService struct and methods live in internal/pdfservice/service.go.
// ---------------------------------------------------------------------------

func TestServiceFileExists(t *testing.T) {
	root := projectRoot(t)

	servicePath := filepath.Join(root, "internal", "pdfservice", "service.go")
	if _, err := os.Stat(servicePath); os.IsNotExist(err) {
		t.Fatal("[P1] 2.3-INTG-003: internal/pdfservice/service.go does not exist")
	}
}

// ---------------------------------------------------------------------------
// 2.3-INTG-004 [P1]: PDFService struct holds *pdfcore.Inspector
// AC#3: PDFService holds a *pdfcore.Inspector instance, not a documents map.
// ---------------------------------------------------------------------------

func TestPDFServiceStructHoldsInspector(t *testing.T) {
	content := readFile(t, "internal/pdfservice/service.go")

	if !strings.Contains(content, "type PDFService struct") {
		t.Fatal("[P1] 2.3-INTG-004: service.go missing PDFService struct")
	}

	if !strings.Contains(content, "*pdfcore.Inspector") {
		t.Error("[P1] 2.3-INTG-004: PDFService does not hold *pdfcore.Inspector")
	}

	// Must NOT have its own documents map
	if strings.Contains(content, "documents map[") {
		t.Error("[P1] 2.3-INTG-004: PDFService has a documents map -- that belongs in pdfcore.Inspector")
	}
}

// ---------------------------------------------------------------------------
// 2.3-INTG-005 [P1]: PDFService has correct method signatures
// AC#1: All five service methods are exported with correct signatures.
// ---------------------------------------------------------------------------

func TestPDFServiceMethodSignatures(t *testing.T) {
	content := readFile(t, "internal/pdfservice/service.go")

	requiredMethods := []struct {
		name      string
		signature string
	}{
		{"OpenFile", "func (s *PDFService) OpenFile("},
		{"CloseDocument", "func (s *PDFService) CloseDocument("},
		{"GetTreeRoot", "func (s *PDFService) GetTreeRoot("},
		{"GetChildren", "func (s *PDFService) GetChildren("},
		{"GetObjectDetail", "func (s *PDFService) GetObjectDetail("},
	}

	for _, m := range requiredMethods {
		if !strings.Contains(content, m.signature) {
			t.Errorf("[P1] 2.3-INTG-005: service.go missing method: %s", m.name)
		}
	}

	// Verify NewPDFService constructor exists
	if !strings.Contains(content, "func NewPDFService()") {
		t.Error("[P1] 2.3-INTG-005: service.go missing NewPDFService() constructor")
	}
}

// ---------------------------------------------------------------------------
// 2.3-INTG-006 [P1]: pdfservice has zero pdfcpu imports (thin adapter)
// AC#3: pdfservice delegates to pdfcore -- it never imports pdfcpu directly.
// ---------------------------------------------------------------------------

func TestPdfserviceZeroPdfcpuImports(t *testing.T) {
	root := projectRoot(t)

	pdfserviceDir := filepath.Join(root, "internal", "pdfservice")
	entries, err := os.ReadDir(pdfserviceDir)
	if err != nil {
		t.Fatalf("[P1] 2.3-INTG-006: cannot read internal/pdfservice/ directory: %v", err)
	}

	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") {
			continue
		}
		if strings.HasSuffix(entry.Name(), "_test.go") {
			continue
		}
		filePath := filepath.Join(pdfserviceDir, entry.Name())
		content, err := os.ReadFile(filePath)
		if err != nil {
			t.Errorf("[P1] cannot read %s: %v", entry.Name(), err)
			continue
		}
		if strings.Contains(string(content), "pdfcpu") {
			t.Errorf("[P1] 2.3-INTG-006: %s imports pdfcpu -- pdfservice must not touch pdfcpu directly", entry.Name())
		}
	}
}

// ---------------------------------------------------------------------------
// 2.3-INTG-007 [P1]: pdfservice has zero Wails imports (consumed by Wails, not dependent)
// AC#3: pdfservice is consumed by Wails via main.go registration, but does not
//       import any Wails packages itself.
// ---------------------------------------------------------------------------

func TestPdfserviceZeroWailsImports(t *testing.T) {
	root := projectRoot(t)

	pdfserviceDir := filepath.Join(root, "internal", "pdfservice")
	entries, err := os.ReadDir(pdfserviceDir)
	if err != nil {
		t.Fatalf("[P1] 2.3-INTG-007: cannot read internal/pdfservice/ directory: %v", err)
	}

	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") {
			continue
		}
		if strings.HasSuffix(entry.Name(), "_test.go") {
			continue
		}
		filePath := filepath.Join(pdfserviceDir, entry.Name())
		content, err := os.ReadFile(filePath)
		if err != nil {
			t.Errorf("[P1] cannot read %s: %v", entry.Name(), err)
			continue
		}
		if strings.Contains(string(content), "wailsapp") {
			t.Errorf("[P1] 2.3-INTG-007: %s imports Wails -- pdfservice must have zero Wails dependencies", entry.Name())
		}
	}
}

// ---------------------------------------------------------------------------
// 2.3-INTG-008 [P1]: Round-trip test: OpenFile -> GetTreeRoot -> GetChildren -> CloseDocument
// AC#1: Full service lifecycle with no errors.
// ---------------------------------------------------------------------------

func TestPDFServiceRoundTrip(t *testing.T) {
	root := projectRoot(t)

	// Run pdfservice unit test that validates full round-trip.
	// Delegates to internal/pdfservice/service_test.go::TestRoundTrip
	// which must exist and test:
	// - OpenFile returns DocumentInfo with non-empty TabID
	// - GetTreeRoot returns root TreeNode
	// - GetChildren("root") returns non-empty slice
	// - CloseDocument returns nil
	// - no errors in any step
	cmd := exec.Command("go", "test", "-v", "-run", "TestRoundTrip", "-count=1", "./internal/pdfservice/...")
	cmd.Dir = root
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("[P1] 2.3-INTG-008: Round-trip test failed:\n%s", string(output))
	}

	if !strings.Contains(string(output), "PASS") {
		t.Fatalf("[P1] 2.3-INTG-008: expected PASS in output but got:\n%s", string(output))
	}
}

// ---------------------------------------------------------------------------
// 2.3-INTG-009 [P1]: OpenFile with nonexistent path returns error
// AC#2: Error propagation from pdfcore through pdfservice.
// ---------------------------------------------------------------------------

func TestPDFServiceOpenFileNonExistent(t *testing.T) {
	root := projectRoot(t)

	cmd := exec.Command("go", "test", "-v", "-run", "TestOpenFileNonExistent", "-count=1", "./internal/pdfservice/...")
	cmd.Dir = root
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("[P1] 2.3-INTG-009: OpenFile nonexistent path test failed:\n%s", string(output))
	}

	if !strings.Contains(string(output), "PASS") {
		t.Fatalf("[P1] 2.3-INTG-009: expected PASS in output but got:\n%s", string(output))
	}
}

// ---------------------------------------------------------------------------
// 2.3-INTG-010 [P1]: OpenFile with malformed PDF returns error
// AC#2: Error propagation for malformed PDF.
// ---------------------------------------------------------------------------

func TestPDFServiceOpenFileMalformed(t *testing.T) {
	root := projectRoot(t)

	cmd := exec.Command("go", "test", "-v", "-run", "TestOpenFileMalformed", "-count=1", "./internal/pdfservice/...")
	cmd.Dir = root
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("[P1] 2.3-INTG-010: OpenFile malformed PDF test failed:\n%s", string(output))
	}

	if !strings.Contains(string(output), "PASS") {
		t.Fatalf("[P1] 2.3-INTG-010: expected PASS in output but got:\n%s", string(output))
	}
}

// ---------------------------------------------------------------------------
// 2.3-INTG-011 [P1]: OpenFile with encrypted PDF returns error
// AC#2: Error propagation for encrypted PDF.
// ---------------------------------------------------------------------------

func TestPDFServiceOpenFileEncrypted(t *testing.T) {
	root := projectRoot(t)

	cmd := exec.Command("go", "test", "-v", "-run", "TestOpenFileEncrypted", "-count=1", "./internal/pdfservice/...")
	cmd.Dir = root
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("[P1] 2.3-INTG-011: OpenFile encrypted PDF test failed:\n%s", string(output))
	}

	if !strings.Contains(string(output), "PASS") {
		t.Fatalf("[P1] 2.3-INTG-011: expected PASS in output but got:\n%s", string(output))
	}
}

// ---------------------------------------------------------------------------
// AC#4 (Task 4): Verification -- project compiles, vet passes
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// 2.3-INTG-012 [P1]: go build ./... compiles the full project
// AC#4.4: Full project compiles with pdfservice integrated.
// ---------------------------------------------------------------------------

func TestProjectCompiles(t *testing.T) {
	root := projectRoot(t)

	// Build packages in story 2-3 scope: internal packages and root main.
	// cmd/cli/ and build/ios/ have pre-existing empty main stubs (no func main)
	// that are out of scope for this story -- exclude them.
	packages := []string{
		"./internal/...",
		".", // root main.go
	}
	for _, pkg := range packages {
		cmd := exec.Command("go", "build", pkg)
		cmd.Dir = root
		output, err := cmd.CombinedOutput()
		if err != nil {
			t.Fatalf("[P1] 2.3-INTG-012: go build %s failed:\n%s", pkg, string(output))
		}
	}
}

// ---------------------------------------------------------------------------
// 2.3-INTG-013 [P1]: go vet ./... passes on the full project
// AC#4.3: No vet warnings.
// ---------------------------------------------------------------------------

func TestProjectVet(t *testing.T) {
	root := projectRoot(t)

	cmd := exec.Command("go", "vet", "./...")
	cmd.Dir = root
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("[P1] 2.3-INTG-013: go vet ./... failed:\n%s", string(output))
	}
}

// ---------------------------------------------------------------------------
// 2.3-INTG-014 [P1]: All pdfservice unit tests pass
// AC#4.1: go test ./internal/pdfservice/... passes.
// ---------------------------------------------------------------------------

func TestAllPdfserviceTestsPass(t *testing.T) {
	root := projectRoot(t)

	cmd := exec.Command("go", "test", "-v", "-count=1", "./internal/pdfservice/...")
	cmd.Dir = root
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("[P1] 2.3-INTG-014: pdfservice test suite failed:\n%s", string(output))
	}

	if !strings.Contains(string(output), "PASS") {
		t.Fatalf("[P1] 2.3-INTG-014: expected PASS in output but got:\n%s", string(output))
	}
}

// ---------------------------------------------------------------------------
// 2.3-INTG-015 [P1]: All pdfcore tests still pass (no regression)
// AC#4.2: Existing pdfcore tests are not broken by pdfservice addition.
// ---------------------------------------------------------------------------

func TestPdfcoreNoRegression(t *testing.T) {
	root := projectRoot(t)

	cmd := exec.Command("go", "test", "-v", "-count=1", "./internal/pdfcore/...")
	cmd.Dir = root
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("[P1] 2.3-INTG-015: pdfcore regression -- tests failed:\n%s", string(output))
	}

	if !strings.Contains(string(output), "PASS") {
		t.Fatalf("[P1] 2.3-INTG-015: expected PASS in output but got:\n%s", string(output))
	}
}

// ---------------------------------------------------------------------------
// 2.3-INTG-016 [P1]: App-shell TestServicesFieldRemoved still passes
// AC#4.2b: The existing app-shell acceptance test must not regress.
// ---------------------------------------------------------------------------

func TestAppShellNoRegression(t *testing.T) {
	root := projectRoot(t)

	// Run from the app-shell directory which has its own go.mod.
	// Cannot use ./tests/app-shell/... from root because of module isolation.
	appShellDir := filepath.Join(root, "tests", "app-shell")
	cmd := exec.Command("go", "test", "-v", "-run", "TestServicesFieldRemoved", "-count=1", "./...")
	cmd.Dir = appShellDir
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("[P1] 2.3-INTG-016: app-shell TestServicesFieldRemoved regressed:\n%s", string(output))
	}

	if !strings.Contains(string(output), "PASS") {
		t.Fatalf("[P1] 2.3-INTG-016: expected PASS in output but got:\n%s", string(output))
	}
}

// ---------------------------------------------------------------------------
// 2.3-INTG-017 [P1]: service_test.go exists in internal/pdfservice/
// AC#3: Unit tests co-located with production code.
// ---------------------------------------------------------------------------

func TestServiceTestFileExists(t *testing.T) {
	root := projectRoot(t)

	testPath := filepath.Join(root, "internal", "pdfservice", "service_test.go")
	if _, err := os.Stat(testPath); os.IsNotExist(err) {
		t.Fatal("[P1] 2.3-INTG-017: internal/pdfservice/service_test.go does not exist")
	}
}
