// Package wails_service_layer_test provides acceptance tests for Wails Service
// Layer -- Bind PDF Core to Frontend.
//
// Test Levels: Unit (Go) -- source file content parsing + delegated test execution.
// No browser interaction required; all criteria are Go package validation.
//
// Run: cd tests/wails-service-layer && go test -v -count=1 ./...
package wails_service_layer_test

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// projectRoot returns the absolute path to the project root directory.
func projectRoot(t *testing.T) string {
	t.Helper()
	dir, err := os.Getwd()
	if err != nil {
		t.Fatalf("failed to get working directory: %v", err)
	}
	for {
		goModPath := filepath.Join(dir, "go.mod")
		if content, err := os.ReadFile(goModPath); err == nil {
			if strings.Contains(string(content), "module unidoc-pdf-debugger") {
				return dir
			}
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatalf("could not find project root (no go.mod with module unidoc-pdf-debugger found)")
		}
		dir = parent
	}
}

// readFile reads a file relative to the project root and returns its content.
func readFile(t *testing.T, relPath string) string {
	t.Helper()
	root := projectRoot(t)
	absPath := filepath.Join(root, relPath)
	content, err := os.ReadFile(absPath)
	if err != nil {
		t.Fatalf("failed to read %s: %v", relPath, err)
	}
	return string(content)
}

// ---------------------------------------------------------------------------
// PDFService struct exists with correct methods
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// PDFService.OpenFile() delegates to Inspector.Open(): Given a valid
// PDF, When PDFService.OpenFile(path) is called,
//       Then it delegates to Inspector.Open() and returns DocumentInfo
//       with non-empty TabID, correct FileName, PageCount > 0.
// ---------------------------------------------------------------------------

func TestPDFServiceOpenFile(t *testing.T) {
	root := projectRoot(t)

	// Run pdfservice unit test that validates OpenFile with valid PDF.
	// Delegates to internal/pdfservice/service_test.go::TestOpenFileValidPDF
	// which must exist and test:
	// - returns non-nil DocumentInfo
	// - DocumentInfo.TabID is non-empty (UUID generated by service)
	// - DocumentInfo.FileName == "minimal.pdf"
	// - DocumentInfo.PageCount >= 1
	// - no error returned
	cmd := exec.Command("go", "test", "-v", "-run", "TestOpenFileValidPDF", "-count=1", "./internal/pdfservice/...")
	cmd.Dir = root
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("PDFService.OpenFile valid PDF test failed:\n%s", string(output))
	}

	if !strings.Contains(string(output), "PASS") {
		t.Fatalf("expected PASS in output but got:\n%s", string(output))
	}
}

// ---------------------------------------------------------------------------
// PDFService.CloseDocument() delegates to Inspector.Close(): Given a previously
// opened document, When CloseDocument(tabID) is called,
//       Then it delegates to Inspector.Close() and returns nil error.
//       And calling again with the same tabID returns ErrDocumentNotFound.
// ---------------------------------------------------------------------------

func TestPDFServiceCloseDocument(t *testing.T) {
	root := projectRoot(t)

	// Run pdfservice unit test that validates CloseDocument.
	// Delegates to internal/pdfservice/service_test.go::TestCloseDocument*
	// which must exist and test:
	// - CloseDocument with valid tabID returns nil
	// - CloseDocument with unknown tabID returns error
	cmd := exec.Command("go", "test", "-v", "-run", "TestCloseDocument", "-count=1", "./internal/pdfservice/...")
	cmd.Dir = root
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("PDFService.CloseDocument test failed:\n%s", string(output))
	}

	if !strings.Contains(string(output), "PASS") {
		t.Fatalf("expected PASS in output but got:\n%s", string(output))
	}
}

// ---------------------------------------------------------------------------
// PDFService.GetTreeRoot() delegates to pdfcore: Given an opened
// document, When GetTreeRoot(tabID) is called,
//       Then it delegates to Inspector.GetTreeRoot() and returns TreeNode
//       with ID "root".
// ---------------------------------------------------------------------------

func TestPDFServiceGetTreeRoot(t *testing.T) {
	root := projectRoot(t)

	// Run pdfservice unit test that validates GetTreeRoot.
	// Delegates to internal/pdfservice/service_test.go::TestGetTreeRoot*
	// which must exist and test:
	// - returns non-nil TreeNode
	// - TreeNode.ID == "root"
	// - no error returned
	// - with unknown tabID returns error
	cmd := exec.Command("go", "test", "-v", "-run", "TestGetTreeRoot", "-count=1", "./internal/pdfservice/...")
	cmd.Dir = root
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("PDFService.GetTreeRoot test failed:\n%s", string(output))
	}

	if !strings.Contains(string(output), "PASS") {
		t.Fatalf("expected PASS in output but got:\n%s", string(output))
	}
}

// ---------------------------------------------------------------------------
// PDFService.GetChildren() delegates to pdfcore: Given an opened document,
// When GetChildren(tabID, "root") is called,
//       Then it delegates to Inspector.GetChildren() and returns non-empty
//       []*TreeNode slice.
// ---------------------------------------------------------------------------

func TestPDFServiceGetChildren(t *testing.T) {
	root := projectRoot(t)

	// Run pdfservice unit test that validates GetChildren.
	// Delegates to internal/pdfservice/service_test.go::TestGetChildren*
	// which must exist and test:
	// - returns non-empty TreeNode slice for valid tabID and "root" nodeID
	// - no error returned
	// - with unknown tabID returns error
	cmd := exec.Command("go", "test", "-v", "-run", "TestGetChildren", "-count=1", "./internal/pdfservice/...")
	cmd.Dir = root
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("PDFService.GetChildren test failed:\n%s", string(output))
	}

	if !strings.Contains(string(output), "PASS") {
		t.Fatalf("expected PASS in output but got:\n%s", string(output))
	}
}

// ---------------------------------------------------------------------------
// PDFService.GetObjectDetail() returns stub error: Given any input,
// When GetObjectDetail(tabID, nodeID) is called,
//       Then it returns a "not implemented" error while it is a stub.
// ---------------------------------------------------------------------------

func TestPDFServiceGetObjectDetail(t *testing.T) {
	root := projectRoot(t)

	// Run pdfservice unit test that validates GetObjectDetail stub.
	// Delegates to internal/pdfservice/service_test.go::TestGetObjectDetail*
	// which must exist and test:
	// - returns error containing "not implemented"
	// - returns nil ObjectDetail
	cmd := exec.Command("go", "test", "-v", "-run", "TestGetObjectDetail", "-count=1", "./internal/pdfservice/...")
	cmd.Dir = root
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("PDFService.GetObjectDetail test failed:\n%s", string(output))
	}

	if !strings.Contains(string(output), "PASS") {
		t.Fatalf("expected PASS in output but got:\n%s", string(output))
	}
}

// ---------------------------------------------------------------------------
// PDFService methods with invalid tabID return error: Given a
// PDFService method, When called with an unknown tabID,
//       Then it returns an error (propagated from pdfcore).
// ---------------------------------------------------------------------------

func TestPDFServiceInvalidTabID(t *testing.T) {
	root := projectRoot(t)

	// Run pdfservice unit tests for invalid tabID scenarios.
	// Delegates to internal/pdfservice/service_test.go tests matching "Unknown"
	// which must exist and test:
	// - CloseDocument with unknown tabID returns error
	// - GetTreeRoot with unknown tabID returns error
	// - GetChildren with unknown tabID returns error
	cmd := exec.Command("go", "test", "-v", "-run", "Unknown", "-count=1", "./internal/pdfservice/...")
	cmd.Dir = root
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("PDFService invalid tabID tests failed:\n%s", string(output))
	}

	if !strings.Contains(string(output), "PASS") {
		t.Fatalf("expected PASS in output but got:\n%s", string(output))
	}
}

// ---------------------------------------------------------------------------
// Wails service registration in main.go
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// PDFService is registered in main.go via app.RegisterService(): Given main.go,
// When reviewed, Then PDFService is created and registered
//       using app.RegisterService() (NOT the Services: field in Options).
// ---------------------------------------------------------------------------


// ---------------------------------------------------------------------------
// main.go does NOT use Services: field in application.Options: The app-shell
// test TestServicesFieldRemoved must still pass.
//       Services: field and application.NewService must not co-occur in Options.
// ---------------------------------------------------------------------------


// ---------------------------------------------------------------------------
// Architecture compliance -- pdfservice is thin adapter
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// service.go exists in internal/pdfservice: PDFService struct and methods
// live in internal/pdfservice/service.go.
// ---------------------------------------------------------------------------

func TestServiceFileExists(t *testing.T) {
	root := projectRoot(t)

	servicePath := filepath.Join(root, "internal", "pdfservice", "service.go")
	if _, err := os.Stat(servicePath); os.IsNotExist(err) {
		t.Fatal("internal/pdfservice/service.go does not exist")
	}
}

// ---------------------------------------------------------------------------
// PDFService struct holds *pdfcore.Inspector: PDFService holds a
// *pdfcore.Inspector instance, not a documents map.
// ---------------------------------------------------------------------------

func TestPDFServiceStructHoldsInspector(t *testing.T) {
	content := readFile(t, "internal/pdfservice/service.go")

	if !strings.Contains(content, "type PDFService struct") {
		t.Fatal("service.go missing PDFService struct")
	}

	if !strings.Contains(content, "*pdfcore.Inspector") {
		t.Error("PDFService does not hold *pdfcore.Inspector")
	}

	// Must NOT have its own documents map
	if strings.Contains(content, "documents map[") {
		t.Error("PDFService has a documents map -- that belongs in pdfcore.Inspector")
	}
}

// ---------------------------------------------------------------------------
// PDFService has correct method signatures: All five service methods
// are exported with correct signatures.
// ---------------------------------------------------------------------------

func TestPDFServiceMethodSignatures(t *testing.T) {
	content := readFile(t, "internal/pdfservice/service.go")

	requiredMethods := []struct {
		name      string
		signature string
	}{
		{"OpenFile", "func (s *PDFService) OpenFile("},
		{"CloseDocument", "func (s *PDFService) CloseDocument("},
		{"GetTreeRoot", "func (s *PDFService) GetTreeRoot("},
		{"GetChildren", "func (s *PDFService) GetChildren("},
		{"GetObjectDetail", "func (s *PDFService) GetObjectDetail("},
	}

	for _, m := range requiredMethods {
		if !strings.Contains(content, m.signature) {
			t.Errorf("service.go missing method: %s", m.name)
		}
	}

	// Verify NewPDFService constructor exists
	if !strings.Contains(content, "func NewPDFService(") {
		t.Error("service.go missing NewPDFService constructor")
	}
}

// ---------------------------------------------------------------------------
// Pdfservice has zero pdfcpu imports (thin adapter): pdfservice delegates to
// pdfcore -- it never imports pdfcpu directly.
// ---------------------------------------------------------------------------

func TestPdfserviceZeroPdfcpuImports(t *testing.T) {
	root := projectRoot(t)

	pdfserviceDir := filepath.Join(root, "internal", "pdfservice")
	entries, err := os.ReadDir(pdfserviceDir)
	if err != nil {
		t.Fatalf("cannot read internal/pdfservice/ directory: %v", err)
	}

	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") {
			continue
		}
		if strings.HasSuffix(entry.Name(), "_test.go") {
			continue
		}
		filePath := filepath.Join(pdfserviceDir, entry.Name())
		content, err := os.ReadFile(filePath)
		if err != nil {
			t.Errorf("cannot read %s: %v", entry.Name(), err)
			continue
		}
		if strings.Contains(string(content), "pdfcpu") {
			t.Errorf("%s imports pdfcpu -- pdfservice must not touch pdfcpu directly", entry.Name())
		}
	}
}

// ---------------------------------------------------------------------------
// Pdfservice is the Wails adapter layer: pdfservice delegates to pdfcore.
// As the Wails adapter layer it may
//       import Wails packages (e.g. application for dialog access). Only
//       pdfcore must remain Wails-free (verified in TestPdfcoreNoRegression).
// ---------------------------------------------------------------------------

func TestPdfserviceIsWailsAdapter(t *testing.T) {
	root := projectRoot(t)

	pdfserviceDir := filepath.Join(root, "internal", "pdfservice")
	entries, err := os.ReadDir(pdfserviceDir)
	if err != nil {
		t.Fatalf("cannot read internal/pdfservice/ directory: %v", err)
	}

	// Ensure pdfservice does NOT import pdfcpu directly (only via pdfcore)
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") {
			continue
		}
		if strings.HasSuffix(entry.Name(), "_test.go") {
			continue
		}
		filePath := filepath.Join(pdfserviceDir, entry.Name())
		content, err := os.ReadFile(filePath)
		if err != nil {
			t.Errorf("cannot read %s: %v", entry.Name(), err)
			continue
		}
		if strings.Contains(string(content), "pdfcpu") {
			t.Errorf("%s imports pdfcpu directly -- pdfservice must delegate to pdfcore", entry.Name())
		}
	}
}

// ---------------------------------------------------------------------------
// Round-trip test: OpenFile -> GetTreeRoot -> GetChildren -> CloseDocument: Full service
// lifecycle with no errors.
// ---------------------------------------------------------------------------

func TestPDFServiceRoundTrip(t *testing.T) {
	root := projectRoot(t)

	// Run pdfservice unit test that validates full round-trip.
	// Delegates to internal/pdfservice/service_test.go::TestRoundTrip
	// which must exist and test:
	// - OpenFile returns DocumentInfo with non-empty TabID
	// - GetTreeRoot returns root TreeNode
	// - GetChildren("root") returns non-empty slice
	// - CloseDocument returns nil
	// - no errors in any step
	cmd := exec.Command("go", "test", "-v", "-run", "TestRoundTrip", "-count=1", "./internal/pdfservice/...")
	cmd.Dir = root
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("Round-trip test failed:\n%s", string(output))
	}

	if !strings.Contains(string(output), "PASS") {
		t.Fatalf("expected PASS in output but got:\n%s", string(output))
	}
}

// ---------------------------------------------------------------------------
// OpenFile with nonexistent path returns error: Error propagation
// from pdfcore through pdfservice.
// ---------------------------------------------------------------------------

func TestPDFServiceOpenFileNonExistent(t *testing.T) {
	root := projectRoot(t)

	cmd := exec.Command("go", "test", "-v", "-run", "TestOpenFileNonExistent", "-count=1", "./internal/pdfservice/...")
	cmd.Dir = root
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("OpenFile nonexistent path test failed:\n%s", string(output))
	}

	if !strings.Contains(string(output), "PASS") {
		t.Fatalf("expected PASS in output but got:\n%s", string(output))
	}
}

// ---------------------------------------------------------------------------
// OpenFile with malformed PDF returns error: Error propagation
// for malformed PDF.
// ---------------------------------------------------------------------------

func TestPDFServiceOpenFileMalformed(t *testing.T) {
	root := projectRoot(t)

	cmd := exec.Command("go", "test", "-v", "-run", "TestOpenFileMalformed", "-count=1", "./internal/pdfservice/...")
	cmd.Dir = root
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("OpenFile malformed PDF test failed:\n%s", string(output))
	}

	if !strings.Contains(string(output), "PASS") {
		t.Fatalf("expected PASS in output but got:\n%s", string(output))
	}
}

// ---------------------------------------------------------------------------
// OpenFile with encrypted PDF returns error: Error propagation
// for encrypted PDF.
// ---------------------------------------------------------------------------

func TestPDFServiceOpenFileEncrypted(t *testing.T) {
	root := projectRoot(t)

	cmd := exec.Command("go", "test", "-v", "-run", "TestOpenFileEncrypted", "-count=1", "./internal/pdfservice/...")
	cmd.Dir = root
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("OpenFile encrypted PDF test failed:\n%s", string(output))
	}

	if !strings.Contains(string(output), "PASS") {
		t.Fatalf("expected PASS in output but got:\n%s", string(output))
	}
}

// ---------------------------------------------------------------------------
// Task 4: Verification -- project compiles, vet passes
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// go build ./... compiles the full project: Full project
// compiles with pdfservice integrated.
// ---------------------------------------------------------------------------

func TestProjectCompiles(t *testing.T) {
	root := projectRoot(t)

	// Build packages in scope: internal packages and root main.
	// cmd/cli/ and build/ios/ have pre-existing empty main stubs (no func main)
	// that are out of scope for this story -- exclude them.
	packages := []string{
		"./internal/...",
		".", // root main.go
	}
	for _, pkg := range packages {
		cmd := exec.Command("go", "build", pkg)
		cmd.Dir = root
		output, err := cmd.CombinedOutput()
		if err != nil {
			t.Fatalf("go build %s failed:\n%s", pkg, string(output))
		}
	}
}

// ---------------------------------------------------------------------------
// go vet ./... passes on the full project: No vet warnings.
// ---------------------------------------------------------------------------

func TestProjectVet(t *testing.T) {
	root := projectRoot(t)

	cmd := exec.Command("go", "vet", "./...")
	cmd.Dir = root
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("go vet./... failed:\n%s", string(output))
	}
}

// ---------------------------------------------------------------------------
// All pdfservice unit tests pass
// go test ./internal/pdfservice/... passes.
// ---------------------------------------------------------------------------

func TestAllPdfserviceTestsPass(t *testing.T) {
	root := projectRoot(t)

	cmd := exec.Command("go", "test", "-v", "-count=1", "./internal/pdfservice/...")
	cmd.Dir = root
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("pdfservice test suite failed:\n%s", string(output))
	}

	if !strings.Contains(string(output), "PASS") {
		t.Fatalf("expected PASS in output but got:\n%s", string(output))
	}
}

// ---------------------------------------------------------------------------
// All pdfcore tests still pass (no regression): Existing pdfcore tests
// are not broken by pdfservice addition.
// ---------------------------------------------------------------------------

func TestPdfcoreNoRegression(t *testing.T) {
	root := projectRoot(t)

	cmd := exec.Command("go", "test", "-v", "-count=1", "./internal/pdfcore/...")
	cmd.Dir = root
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("pdfcore regression -- tests failed:\n%s", string(output))
	}

	if !strings.Contains(string(output), "PASS") {
		t.Fatalf("expected PASS in output but got:\n%s", string(output))
	}
}

// ---------------------------------------------------------------------------
// App-shell TestServicesFieldRemoved still passes b: The existing
// app-shell acceptance test must not regress.
// ---------------------------------------------------------------------------

func TestAppShellNoRegression(t *testing.T) {
	root := projectRoot(t)

	// Run from the app-shell directory which has its own go.mod.
	// Cannot use ./tests/app-shell/... from root because of module isolation.
	appShellDir := filepath.Join(root, "tests", "app-shell")
	cmd := exec.Command("go", "test", "-v", "-run", "TestServicesFieldRemoved", "-count=1", "./...")
	cmd.Dir = appShellDir
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("app-shell TestServicesFieldRemoved regressed:\n%s", string(output))
	}

	if !strings.Contains(string(output), "PASS") {
		t.Fatalf("expected PASS in output but got:\n%s", string(output))
	}
}

// ---------------------------------------------------------------------------
// service_test.go exists in internal/pdfservice: Unit tests
// co-located with production code.
// ---------------------------------------------------------------------------

func TestServiceTestFileExists(t *testing.T) {
	root := projectRoot(t)

	testPath := filepath.Join(root, "internal", "pdfservice", "service_test.go")
	if _, err := os.Stat(testPath); os.IsNotExist(err) {
		t.Fatal("internal/pdfservice/service_test.go does not exist")
	}
}
