// Expose existing pdfcore views as CLI commands.
//
// Covers the reference-taking dump subcommands (font, image, source,
// reverserefs). Black-box: build the CLI, run as a subprocess.
//
// Test level: Integration (Go) -- CLI binary build + execution. No browser
// interaction; every criterion is CLI binary I/O validation, so per the test
// pyramid these live at the integration level, not E2E.
//
// Fixtures (testdata/, generated by testdata/generate_test.go):
//   - image-xobject.pdf : obj "4 0 R" is a /Subtype /Image XObject;
//                         obj "3 0 R" is a /Type /Page dict (non-image).
//   - fonts-mixed.pdf   : obj "4 0 R" is a /Type /Font dict;
//                         obj "1 0 R" is the /Type /Catalog (non-font).
//
// Covers: (ref-taking payloads + both ref forms), (image --metadata), (source
// default JSON vs --raw), (non-error payloads at exit 0 + missing --ref usage
// error).
//
// Run: cd tests/cli-views && go test -v -count=1 ./...
package cli_views_test

import (
	"encoding/json"
	"path/filepath"
	"strings"
	"testing"
)

// ---------------------------------------------------------------------------
// `dump font --ref "4 0 R" fonts-mixed.pdf` emits a FontView payload as JSON
// on stdout with exit 0. FontView always carries the `kind`, `detail`, and
// `roster` keys (detail/roster are non-omitempty pointers); for a real /Type
// /Font dict kind is "detail".
// ---------------------------------------------------------------------------

func TestFontDump_FontDict_OutputsFontViewJSON(t *testing.T) {
	bin := buildCLI(t)
	pdfPath := filepath.Join(testdataDir(t), "fonts-mixed.pdf")

	stdout, _, exitCode := runCLI(t, bin, "dump", "font", "--json", "--ref", "4 0 R", pdfPath)

	if exitCode != 0 {
		t.Fatalf("expected exit code 0, got %d", exitCode)
	}

	var view map[string]json.RawMessage
	mustParseJSON(t, stdout, &view)

	for _, key := range []string{"kind", "detail", "roster"} {
		if _, ok := view[key]; !ok {
			t.Errorf("FontView JSON missing key %q", key)
		}
	}

	var kind string
	_ = json.Unmarshal(view["kind"], &kind)
	if kind != "detail" {
		t.Errorf("expected kind=\"detail\" for a /Type /Font dict, got %q", kind)
	}
}

// ---------------------------------------------------------------------------
// `dump image --ref "4 0 R" image-xobject.pdf` emits an ImageData payload as
// JSON with exit 0. For a real image XObject the `error` field is empty and
// width/height/colorSpace are populated.
// ---------------------------------------------------------------------------

func TestImageDump_ImageXObject_OutputsImageDataJSON(t *testing.T) {
	bin := buildCLI(t)
	pdfPath := filepath.Join(testdataDir(t), "image-xobject.pdf")

	stdout, _, exitCode := runCLI(t, bin, "dump", "image", "--json", "--ref", "4 0 R", pdfPath)

	if exitCode != 0 {
		t.Fatalf("expected exit code 0, got %d", exitCode)
	}

	var img map[string]any
	mustParseJSON(t, stdout, &img)

	if errStr, _ := img["error"].(string); errStr != "" {
		t.Errorf("expected empty error for a real image XObject, got %q", errStr)
	}
	for _, key := range []string{"nodeId", "objectRef", "width", "height", "colorSpace", "base64"} {
		if _, ok := img[key]; !ok {
			t.Errorf("ImageData JSON missing key %q", key)
		}
	}
	if w, _ := img["width"].(float64); w <= 0 {
		t.Errorf("expected positive width, got %v", img["width"])
	}
}

// ---------------------------------------------------------------------------
// `dump source --ref "4 0 R" image-xobject.pdf` (default) emits JSON
// {"objectRef","source"} with exit 0. objectRef is the canonical "N G R" form
// built by the CLI; source is the reserialized PDF syntax (contains the "N G
// obj" envelope).
// ---------------------------------------------------------------------------

func TestSourceDump_Default_OutputsObjectRefAndSourceJSON(t *testing.T) {
	bin := buildCLI(t)
	pdfPath := filepath.Join(testdataDir(t), "image-xobject.pdf")

	stdout, _, exitCode := runCLI(t, bin, "dump", "source", "--json", "--ref", "4 0 R", pdfPath)

	if exitCode != 0 {
		t.Fatalf("expected exit code 0, got %d", exitCode)
	}

	var env struct {
		ObjectRef string `json:"objectRef"`
		Source    string `json:"source"`
	}
	mustParseJSON(t, stdout, &env)

	if env.ObjectRef != "4 0 R" {
		t.Errorf("expected objectRef \"4 0 R\", got %q", env.ObjectRef)
	}
	if !strings.Contains(env.Source, "4 0 obj") {
		t.Errorf("source should contain the \"4 0 obj\" envelope; got:\n%.300s", env.Source)
	}
}

// ---------------------------------------------------------------------------
// `dump reverserefs --ref REF` emits a JSON array of ReverseRef. The Page
// dict (obj 3) in image-xobject.pdf is referenced by the Pages tree, so it
// has at least one inbound edge; each edge carries parentNodeId / parentRef
// / path.
// ---------------------------------------------------------------------------

func TestReverseRefsDump_ReferencedObject_OutputsNonEmptyArray(t *testing.T) {
	bin := buildCLI(t)
	pdfPath := filepath.Join(testdataDir(t), "image-xobject.pdf")

	stdout, _, exitCode := runCLI(t, bin, "dump", "reverserefs", "--json", "--ref", "3 0 R", pdfPath)

	if exitCode != 0 {
		t.Fatalf("expected exit code 0, got %d", exitCode)
	}

	var refs []map[string]any
	mustParseJSON(t, stdout, &refs)

	if len(refs) == 0 {
		t.Fatalf("expected at least one reverse ref for the page dict (referenced by the Pages tree)")
	}
	for _, key := range []string{"parentNodeId", "parentRef", "path"} {
		if _, ok := refs[0][key]; !ok {
			t.Errorf("ReverseRef entry missing key %q", key)
		}
	}
}

// ---------------------------------------------------------------------------
// ref-taking commands accept BOTH the "N G R" and obj:G:N forms (reusing
// 11-3's liberal parseObjectRef). For obj 4 0, the obj:G:N id is "obj:0:4"
// (gen first, num second). Output must be equivalent JSON regardless of the
// input form.
// ---------------------------------------------------------------------------

func TestByRef_BothRefForms_Equivalent(t *testing.T) {
	bin := buildCLI(t)

	cases := []struct {
		name    string
		args    []string // resource + flags (ref injected per form)
		pdf     string
		refNGR  string
		refObj  string
	}{
		{"font", []string{"font"}, "fonts-mixed.pdf", "4 0 R", "obj:0:4"},
		{"image", []string{"image"}, "image-xobject.pdf", "4 0 R", "obj:0:4"},
		{"source", []string{"source"}, "image-xobject.pdf", "4 0 R", "obj:0:4"},
		{"reverserefs", []string{"reverserefs"}, "image-xobject.pdf", "3 0 R", "obj:0:3"},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			pdfPath := filepath.Join(testdataDir(t), tc.pdf)

			// Compare the JSON contract across both ref forms (--json opt-in).
			ngrArgs := append([]string{"dump"}, tc.args...)
			ngrArgs = append(ngrArgs, "--json", "--ref", tc.refNGR, pdfPath)
			outNGR, _, ecNGR := runCLI(t, bin, ngrArgs...)
			if ecNGR != 0 {
				t.Fatalf("%s: \"N G R\" form exit %d", tc.name, ecNGR)
			}

			objArgs := append([]string{"dump"}, tc.args...)
			objArgs = append(objArgs, "--json", "--ref", tc.refObj, pdfPath)
			outObj, _, ecObj := runCLI(t, bin, objArgs...)
			if ecObj != 0 {
				t.Fatalf("%s: obj:G:N form exit %d", tc.name, ecObj)
			}

			// Normalize both through generic JSON to ignore formatting.
			var a, b any
			mustParseJSON(t, outNGR, &a)
			mustParseJSON(t, outObj, &b)
			ja, _ := json.Marshal(a)
			jb, _ := json.Marshal(b)
			if string(ja) != string(jb) {
				t.Errorf("%s: the two ref forms produced different output\n N G R: %s\n obj: %s", tc.name, ja, jb)
			}
		})
	}
}

// ---------------------------------------------------------------------------
// `dump image --ref REF --metadata` OMITS the
// `base64` key entirely (NOT "base64":"") while keeping width/height/etc;
// Without --metadata the full base64 value is present and non-empty. (If the
// team relaxes to "blank the value", flip the omission assertion
//  to require base64 == "" -- see the Decision note in the story.)
// ---------------------------------------------------------------------------

func TestImageDump_MetadataFlag_OmitsBase64(t *testing.T) {
	bin := buildCLI(t)
	pdfPath := filepath.Join(testdataDir(t), "image-xobject.pdf")

	// With --metadata (JSON): base64 key absent, other metadata present.
	metaOut, _, ecMeta := runCLI(t, bin, "dump", "image", "--json", "--metadata", "--ref", "4 0 R", pdfPath)
	if ecMeta != 0 {
		t.Fatalf("--metadata run exit %d", ecMeta)
	}
	var metaRaw map[string]json.RawMessage
	mustParseJSON(t, metaOut, &metaRaw)
	if _, present := metaRaw["base64"]; present {
		t.Errorf("--metadata output must OMIT the base64 key entirely, but it is present")
	}
	for _, key := range []string{"width", "height", "colorSpace"} {
		if _, ok := metaRaw[key]; !ok {
			t.Errorf("--metadata output missing metadata key %q", key)
		}
	}

	// Without --metadata (JSON): base64 present and non-empty.
	fullOut, _, ecFull := runCLI(t, bin, "dump", "image", "--json", "--ref", "4 0 R", pdfPath)
	if ecFull != 0 {
		t.Fatalf("default run exit %d", ecFull)
	}
	var full map[string]any
	mustParseJSON(t, fullOut, &full)
	if b, _ := full["base64"].(string); b == "" {
		t.Errorf("default output should include a non-empty base64 value")
	}
}

// ---------------------------------------------------------------------------
// / Review #1 regression guard: the `--metadata` projection must preserve
// every surviving (non-base64) field byte-for-byte against the full form. The
// metadata output must equal the full output with only the `base64` key
// deleted. This locks the Review #1 fix (the projection uses
// map[string]json.RawMessage, NOT map[string]any -- the latter would relabel
// every integer field, e.g. width/height/bitsPerComponent, as a float64 and
// silently diverge from the full form). Key-presence alone (INTG-006) does
// not catch that numeric-laundering regression.
// ---------------------------------------------------------------------------

func TestImageDump_MetadataFlag_PreservesSurvivingFieldsVerbatim(t *testing.T) {
	bin := buildCLI(t)
	pdfPath := filepath.Join(testdataDir(t), "image-xobject.pdf")

	fullOut, _, ecFull := runCLI(t, bin, "dump", "image", "--json", "--ref", "4 0 R", pdfPath)
	if ecFull != 0 {
		t.Fatalf("default run exit %d", ecFull)
	}
	metaOut, _, ecMeta := runCLI(t, bin, "dump", "image", "--json", "--metadata", "--ref", "4 0 R", pdfPath)
	if ecMeta != 0 {
		t.Fatalf("--metadata run exit %d", ecMeta)
	}

	// Decode both into raw-message maps so we compare the exact serialized value
	// of each surviving field (a float64-laundered int would differ here).
	var full, meta map[string]json.RawMessage
	mustParseJSON(t, fullOut, &full)
	mustParseJSON(t, metaOut, &meta)

	// Expected metadata view = full view with the base64 key removed.
	delete(full, "base64")

	if len(full) != len(meta) {
		t.Fatalf("metadata view has %d keys, expected %d (full minus base64)", len(meta), len(full))
	}
	for key, want := range full {
		got, ok := meta[key]
		if !ok {
			t.Errorf("metadata view missing field %q present in full view", key)
			continue
		}
		// Byte-for-byte equality of the serialized value. An int re-emitted as a
		// float64 (e.g. 8 -> 8 is the same, but 1e6 -> 1000000 vs 1e+06, and any
		// fractional artifact) would break this; more importantly it pins that no
		// surviving field is re-typed by the projection.
		if string(got) != string(want) {
			t.Errorf("field %q diverged between full and --metadata forms\n full: %s\n meta: %s", key, want, got)
		}
	}
}

// ---------------------------------------------------------------------------
// `dump source --ref REF --raw` writes the verbatim reserialized source bytes
// to stdout (NOT JSON), mirroring `dump stream --raw`. The raw bytes equal
// the `source` field of the default JSON form.
// ---------------------------------------------------------------------------

func TestSourceDump_Raw_WritesVerbatimSource(t *testing.T) {
	bin := buildCLI(t)
	pdfPath := filepath.Join(testdataDir(t), "image-xobject.pdf")

	rawOut, _, ecRaw := runCLI(t, bin, "dump", "source", "--raw", "--ref", "4 0 R", pdfPath)
	if ecRaw != 0 {
		t.Fatalf("--raw run exit %d", ecRaw)
	}
	// Raw output is not JSON-wrapped.
	if json.Valid([]byte(strings.TrimSpace(rawOut))) && strings.HasPrefix(strings.TrimSpace(rawOut), "{") {
		t.Errorf("--raw output should be verbatim source, not a JSON object:\n%.200s", rawOut)
	}
	if !strings.Contains(rawOut, "4 0 obj") {
		t.Errorf("--raw output should contain the \"4 0 obj\" envelope:\n%.200s", rawOut)
	}

	// The raw bytes must equal the --json form's `source` field.
	jsonOut, _, ecJSON := runCLI(t, bin, "dump", "source", "--json", "--ref", "4 0 R", pdfPath)
	if ecJSON != 0 {
		t.Fatalf("--json run exit %d", ecJSON)
	}
	var env struct {
		Source string `json:"source"`
	}
	mustParseJSON(t, jsonOut, &env)
	if rawOut != env.Source {
		t.Errorf("--raw stdout should equal the default form's source field\n--raw: %.200q\nsource: %.200q", rawOut, env.Source)
	}
}

// ---------------------------------------------------------------------------
// type-mismatch / nonexistent refs surface the underlying method's payload
// FAITHFULLY with exit 0 (NOT a synthetic error):
//   - dump font on a non-font (the catalog, obj 1) -> {"kind":"neither",...}
//   - dump image on a non-image (the page dict, obj 3) -> populated `error`
//   - dump source on an unresolved ref -> "N G obj\nnull\nendobj" envelope
//   - dump reverserefs on an unreferenced/nonexistent obj -> []
// ---------------------------------------------------------------------------

func TestByRef_TypeMismatch_NonErrorPayloadExit0(t *testing.T) {
	bin := buildCLI(t)
	imgPDF := filepath.Join(testdataDir(t), "image-xobject.pdf")
	fontPDF := filepath.Join(testdataDir(t), "fonts-mixed.pdf")

	t.Run("font_on_non_font_is_neither", func(t *testing.T) {
		// obj 1 in fonts-mixed.pdf is the /Type /Catalog, not a font.
		stdout, _, ec := runCLI(t, bin, "dump", "font", "--json", "--ref", "1 0 R", fontPDF)
		if ec != 0 {
			t.Fatalf("font: expected exit 0 (non-error), got %d", ec)
		}
		var view struct {
			Kind string `json:"kind"`
		}
		mustParseJSON(t, stdout, &view)
		if view.Kind != "neither" {
			t.Errorf("font: expected kind=\"neither\" on a non-font, got %q", view.Kind)
		}
	})

	t.Run("image_on_non_image_has_error_field", func(t *testing.T) {
		// obj 3 in image-xobject.pdf is the /Type /Page dict, not an image.
		stdout, _, ec := runCLI(t, bin, "dump", "image", "--json", "--ref", "3 0 R", imgPDF)
		if ec != 0 {
			t.Fatalf("image: expected exit 0 (non-error), got %d", ec)
		}
		var img struct {
			Error string `json:"error"`
		}
		mustParseJSON(t, stdout, &img)
		if img.Error == "" {
			t.Errorf("image: expected a populated error field on a non-image, got empty")
		}
	})

	t.Run("source_on_unresolved_ref_is_null_envelope", func(t *testing.T) {
		// A high, nonexistent object number resolves to nil -> null envelope.
		stdout, _, ec := runCLI(t, bin, "dump", "source", "--json", "--ref", "999 0 R", imgPDF)
		if ec != 0 {
			t.Fatalf("source: expected exit 0 (non-error), got %d", ec)
		}
		var env struct {
			Source string `json:"source"`
		}
		mustParseJSON(t, stdout, &env)
		if !strings.Contains(env.Source, "null") || !strings.Contains(env.Source, "obj") {
			t.Errorf("source: expected the null-body envelope (\"N G obj\\nnull\\nendobj\"), got:\n%.200s", env.Source)
		}
	})

	t.Run("reverserefs_on_unreferenced_is_empty_array", func(t *testing.T) {
		// A high, nonexistent object number has no inbound edges -> [].
		stdout, _, ec := runCLI(t, bin, "dump", "reverserefs", "--json", "--ref", "999 0 R", imgPDF)
		if ec != 0 {
			t.Fatalf("reverserefs: expected exit 0 (non-error), got %d", ec)
		}
		var refs []any
		mustParseJSON(t, stdout, &refs)
		if len(refs) != 0 {
			t.Errorf("reverserefs: expected [] for an unreferenced object, got %d entries", len(refs))
		}
	})
}

// ---------------------------------------------------------------------------
// A missing --ref on a ref-taking command exits 1 (usage error) with a
// RESOURCE-SPECIFIC worked-example message naming the command and its --ref
// form; stdout is empty.
//
// The discriminator against the generic usage menu is that the message names
// the resource: `dump font`/`dump image`/etc., not the menu that lists them all.
// ---------------------------------------------------------------------------

func TestByRef_MissingRefFlag_UsageError(t *testing.T) {
	bin := buildCLI(t)
	imgPDF := filepath.Join(testdataDir(t), "image-xobject.pdf")

	for _, resource := range []string{"font", "image", "source", "reverserefs"} {
		t.Run(resource, func(t *testing.T) {
			stdout, stderr, ec := runCLI(t, bin, "dump", resource, imgPDF)
			if ec != 1 {
				t.Errorf("%s: expected exit code 1 (usage), got %d", resource, ec)
			}
			if strings.TrimSpace(stdout) != "" {
				t.Errorf("%s: stdout should be empty on usage error, got: %s", resource, stdout)
			}
			// Worked example must name THIS command and the --ref form, not the
			// generic menu. e.g. `Usage: pdfdebug dump font ... --ref "N G R" <file>`.
			if !strings.Contains(stderr, "dump "+resource) {
				t.Errorf("%s: stderr should name the specific command (`dump %s`), got:\n%s", resource, resource, stderr)
			}
			if !strings.Contains(stderr, "--ref") {
				t.Errorf("%s: stderr worked example should mention --ref, got:\n%s", resource, stderr)
			}
		})
	}
}

// ---------------------------------------------------------------------------
// Exit 2 is reserved for genuine Go errors. A nonexistent file path on a
// ref-taking command produces a JSON error on stderr and exit 2 (like
// dump object / dump stream), with empty stdout.
// ---------------------------------------------------------------------------

func TestByRef_NonexistentFile_JSONErrorExit2(t *testing.T) {
	bin := buildCLI(t)

	for _, resource := range []string{"font", "image", "source", "reverserefs"} {
		t.Run(resource, func(t *testing.T) {
			stdout, stderr, ec := runCLI(t, bin, "dump", resource, "--ref", "1 0 R", "/nonexistent/path/fake.pdf")
			if ec != 2 {
				t.Errorf("%s: expected exit code 2 for file error, got %d", resource, ec)
			}
			if strings.TrimSpace(stdout) != "" {
				t.Errorf("%s: stdout should be empty on error, got: %s", resource, stdout)
			}
			var errObj map[string]string
			if err := json.Unmarshal([]byte(strings.TrimSpace(stderr)), &errObj); err != nil {
				t.Fatalf("%s: stderr is not valid JSON: %v\nraw: %s", resource, err, stderr)
			}
			if _, ok := errObj["error"]; !ok {
				t.Errorf("%s: stderr JSON missing 'error' key", resource)
			}
		})
	}
}

// ---------------------------------------------------------------------------
// A malformed --ref on a ref-taking command exits 1 (usage) -- parseObjectRef
// rejects it before any PDF work, surfacing the shared refFormatHint (which
// names the "N G R" / obj:G:N forms).
//
// The discriminator is the hint substring ("N G R") inside the JSON error,
// which only appears once the command reaches parseObjectRef.
// ---------------------------------------------------------------------------

func TestByRef_MalformedRef_UsageError(t *testing.T) {
	bin := buildCLI(t)
	imgPDF := filepath.Join(testdataDir(t), "image-xobject.pdf")

	for _, resource := range []string{"font", "image", "source", "reverserefs"} {
		t.Run(resource, func(t *testing.T) {
			stdout, stderr, ec := runCLI(t, bin, "dump", resource, "--ref", "not-a-ref", imgPDF)
			if ec != 1 {
				t.Errorf("%s: expected exit code 1 (usage) for malformed ref, got %d", resource, ec)
			}
			if strings.TrimSpace(stdout) != "" {
				t.Errorf("%s: stdout should be empty on malformed ref, got: %s", resource, stdout)
			}
			// parseObjectRef rejects via writeJSONError with the shared
			// refFormatHint. Its distinctive "obj:G:N id form" phrase is absent
			// from the generic usage menu, so this fails until the command is
			// wired to parseObjectRef.
			var errObj map[string]string
			if err := json.Unmarshal([]byte(trimSpace(stderr)), &errObj); err != nil {
				t.Fatalf("%s: stderr should be a JSON error object from parseObjectRef: %v\nraw: %s", resource, err, stderr)
			}
			if !strings.Contains(errObj["error"], "obj:G:N") {
				t.Errorf("%s: error message should carry the ref-format hint naming the obj:G:N form, got: %q", resource, errObj["error"])
			}
		})
	}
}

// ---------------------------------------------------------------------------
// 13.1: plain-text default siblings for the ref-taking commands. WITHOUT
// --json the output is human-readable (aligned key/value for font/image,
// reserialized source for source, an aligned table for reverserefs) and must
// NOT be JSON. Assertions are STRUCTURAL.
// ---------------------------------------------------------------------------

func TestFontDump_PlainTextDefault(t *testing.T) {
	bin := buildCLI(t)
	pdfPath := filepath.Join(testdataDir(t), "fonts-mixed.pdf")

	stdout, _, ec := runCLI(t, bin, "dump", "font", "--ref", "4 0 R", pdfPath)
	if ec != 0 {
		t.Fatalf("[13.1] font plain: expected exit 0, got %d", ec)
	}
	if isJSONObject(stdout) {
		t.Fatalf("[13.1] font plain: default output must be plain text, not JSON:\n%.200s", stdout)
	}
	// A /Type /Font dict (kind detail) -> aligned record naming the base font.
	if !strings.Contains(stdout, "BaseFont:") {
		t.Errorf("[13.1] font plain: expected an aligned BaseFont: row\n%s", stdout)
	}
}

func TestImageDump_PlainTextDefault(t *testing.T) {
	bin := buildCLI(t)
	pdfPath := filepath.Join(testdataDir(t), "image-xobject.pdf")

	stdout, _, ec := runCLI(t, bin, "dump", "image", "--ref", "4 0 R", pdfPath)
	if ec != 0 {
		t.Fatalf("[13.1] image plain: expected exit 0, got %d", ec)
	}
	if isJSONObject(stdout) {
		t.Fatalf("[13.1] image plain: default output must be plain text, not JSON:\n%.200s", stdout)
	}
	for _, key := range []string{"Width:", "Height:", "ColorSpace:"} {
		if !strings.Contains(stdout, key) {
			t.Errorf("[13.1] image plain: expected an aligned %q row\n%s", key, stdout)
		}
	}
	// The base64 payload must NOT flood the plain-text view.
	if strings.Contains(stdout, "base64") {
		t.Errorf("[13.1] image plain: plain output should not carry the base64 payload\n%.200s", stdout)
	}
}

func TestSourceDump_PlainTextDefault(t *testing.T) {
	bin := buildCLI(t)
	pdfPath := filepath.Join(testdataDir(t), "image-xobject.pdf")

	stdout, _, ec := runCLI(t, bin, "dump", "source", "--ref", "4 0 R", pdfPath)
	if ec != 0 {
		t.Fatalf("[13.1] source plain: expected exit 0, got %d", ec)
	}
	if isJSONObject(stdout) {
		t.Fatalf("[13.1] source plain: default output must be the reserialized source, not JSON:\n%.200s", stdout)
	}
	// The plain default is the reserialized PDF source: it carries the obj envelope.
	if !strings.Contains(stdout, "4 0 obj") {
		t.Errorf("[13.1] source plain: expected the \"4 0 obj\" envelope\n%.200s", stdout)
	}
}

func TestReverseRefsDump_PlainTextDefault(t *testing.T) {
	bin := buildCLI(t)
	pdfPath := filepath.Join(testdataDir(t), "image-xobject.pdf")

	stdout, _, ec := runCLI(t, bin, "dump", "reverserefs", "--ref", "3 0 R", pdfPath)
	if ec != 0 {
		t.Fatalf("[13.1] reverserefs plain: expected exit 0, got %d", ec)
	}
	if isJSONObject(stdout) {
		t.Fatalf("[13.1] reverserefs plain: default output must be plain text, not JSON:\n%.200s", stdout)
	}
	// Aligned table: header row naming the PARENT and PATH columns.
	if !strings.Contains(stdout, "PARENT") || !strings.Contains(stdout, "PATH") {
		t.Errorf("[13.1] reverserefs plain: expected a header row with PARENT/PATH columns\n%s", stdout)
	}
}

// isJSONObject reports whether s (trimmed) begins with a JSON object/array
// delimiter and parses as JSON -- the discriminator for "this is JSON, not the
// plain-text default".
func isJSONObject(s string) bool {
	t := strings.TrimSpace(s)
	if t == "" {
		return false
	}
	if t[0] != '{' && t[0] != '[' {
		return false
	}
	return json.Valid([]byte(t))
}
